########################## IDC-WEB公共配置 #######################################
server:
  port: 9091 #部署信息（IDC界面端口）
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf:                                                               # THYMELEAF（模板引擎配置）
    cache: false
    prefix: classpath:/view/
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
  messages:
    basename: i18n/message                                                 # 指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    cache-seconds: 3600                                                    # 设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    encoding: UTF-8
  freemarker:                                                              # FREEMARKER（模板引擎配置）
    template-loader-path: classpath:/templates/
    request-context-attribute: request

  resources:                                                               # 静态资源（标识资源路径）
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,

eureka:
  client:
    service-url:
      defaultZone: http://www.vivtoum.tech:1001/eureka/                    # 部署信息（注册中心地址）
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

blog-svc:
  url: http://localhost:12345

blog-web:
  url: http://localhost:${server.port}

jasypt:
  encryptor:
    password: vivtoum
---
###################### BLOG-WEB开发环境配置 #########################
spring:
  profiles: dev                                                 # 部署信息（选择配置分支）
  redis:
    host: www.vivtoum.tech                                      # 部署信息（Redis主机地址）
    port: 6379                                                  # 部署信息（Redis访问端口）
    password: ENC(04m+YpfOe/NCVhBy40CRFQuE8Asy+gEv)             # 部署信息（Redis认证密码）
root:
  path: ./upload/

url:
  watsons-ept:
    login: http://wtccn-gz-ept/Portal/Login.aspx    # e-portal（登录地址）
---
###################### BLOG-WEB测试环境配置 #########################
spring:
  profiles: test                                                # 部署信息（选择配置分支）
  redis:
    host: 192.168.122.85                                        # 部署信息（Redis主机地址）
    port: 6379                                                  # 部署信息（Redis访问端口）
    password: Cache##85                                         # 部署信息（Redis认证密码）